### ISSUE TITLE
A potential risk in the coralogix-aws-shipper which can be used to privilege escalation.

### ISSUE THREAD

**Issue by zolaer9527** [coralogix/coralogix-aws-shipper#112]
Hello! I found a potential risk in the coralogix-aws-shipper when I deployed it in the AWS Serverless Application Repository. A malicious can leverage the "iam:\*" and "lambda:\*" permissions to escalate permission.

## Details Analysis:
The coralogix-aws-shipper application creates a function named CustomResourceLambdaTriggerFunction, and the associated role is assigned policies with permissions such as "iam:\*" and "lambda:\*" for all resources. It's too dangerous that the function role has so many excessive permissions. A malicious user can use these permissions in multiple ways to enhance their privileges. For example, he/she can leverage the  "iam:AttachRolePolicy" permission to escalate privileges by attaching a policy to a role that they have access to, adding the permissions of that policy to the attacker. Or he/she can leverage the "iam:PutUserPolicy" permission to escalate privileges by creating or updating an inline policy for a user to which he/she has access, adding the permissions of that policy to the attacker. Anyway, these granted permissions are terrible. This poses a significant security risk to the account used to deploy the application.

## Mitigation Discussion:
1. Use finer-grained authorization methods. And use the specific resource names to replace the "\*".
2. Add a permissions boundary to restrict the permission.
3. The permissions for IAM resources should be removed if they do not affect normal functionality.

## Question:
1. Is it a real issue in the coralogix-aws-shipper?
2. If it's a real issue, can any of my suggestions be used to solve this problem?
4. If my suggestions could be used to solve this problem, could you give me a CVE number to award my discovery?

By the way, I have followed security policy to report (suspected) security vulnerabilities to [security@coralogix.com](mailto:security@coralogix.com) on July 11th. However, I haven't received a response, so I can only raise an issue here. I apologize for any inconvenience this may have caused you.

Looking forward to hearing back from you.

Best Regards,

**Comment by royfur** [comment]
Hi

Thanks for updating us and sorry for missing your e-mail
This is something that is known to us and in our plans to improve some of it was already changed in latests versions and some is still in the plan
I will go head and close this issue

**Comment by zolaer9527** [comment]
Hello,

Glad to know you are aware of this issue. It's a significant security vulnerability. So once you address it, would you be able to provide a CVE for rewarding my report?
I'm looking forward to your reply.

**Comment by mistermocha** [comment]
Thank you for your report. We always appreciate being made aware of security issues. That said, had begun to implement this fix prior to your email on July 11th. It was merged public since (https://github.com/coralogix/coralogix-aws-shipper/pull/106). The threat model of this vulnerability is relatively low as well, as such a bad actor would already have sufficient access to these permission levels.

**Comment by zolaer9527** [comment]
Hello,
 
I  have submitted [another issue](https://github.com/coralogix/coralogix-aws-serverless/issues/159) about the [coralogix-aws-serverless](https://github.com/coralogix/coralogix-aws-serverless) of the Coralogix, but I haven't received any response, can you help me?
