### ISSUE TITLE
Feature Request: Add cloudwatch logs metadata

### ISSUE THREAD

**Issue by yosefha-pg** [coralogix/coralogix-aws-shipper#62]
### The issue

We would like to export metadata for every cloudwatch loggroup which shows the cloudwatch loggroup name
We do not want to use application or subsystem fields for this, since we are using those fields for something else (environment, and product/division name)

We are ok with the compromise of setting the subsystem name dynamically to the cloudwatch loggroup but with an allowance to append strings by prefix or suffix.

### What was considered

Automatically filling subsystem field with ${loggroup}-${division}. This does not appear to be possible. Even though it looks like subsystem can be filled to the loggroup automatically, it appears to be a binary approach (either its enabled or disabled, but no strings can be prepended or appended to it)

Creating custom log preprocessors either by attaching them to Kinesis stream so that all messages are enriched, or by filtering all logs to cloudwatch through a custom enricher. We decided to avoid this approach as it requires alot of development work and seems redundant considering the ability to enrich cloudwatch logs exists already.

We considered using ` add_metadata   = "stream_name"` instead of cloudwatch loggroup names, but this falls short for a few reasons
1. It is not always easy to view all log streams from a single cloudwatch log group together
2. stream names often don't properly identify the logs being sent
3. stream name prefixes can be confused with multiple log groups (e.g. streams from multiple eks clusters might look similar)

### Feature Proposal

Today, it is possible to enrich cloudwatch logs using the terraform option called 'add_metadata'

`add_metadata  = "stream_name"`

For s3 you can similarly enrich logs with multiple fields of s3 object and bucket. 

We would like to add one more field to all cloudwatch logs: the cloudwatch loggroup. The implementation would probably look like:

 `add_metadata  = "stream_name,loggroup_name"`

The effect would be the addition of another field in all cloudwatch logs in which `loggroup_name == <the name of the cloudwatch loggroup>`

**Comment by juan-coralogix** [comment]
HI @yosefha-pg, 
Thanks for the detailed explanation.
Your proposal looks like a good idea, and we can add it to our backlog and push it in a future release.

**Comment by juan-coralogix** [comment]
Hi @yosefha-pg, version 1.0.1 just been published. The Cloudwatch Loggroup name has been added to the metadata options. 
Hope it helps, let us know if anything else can be improved. 
Thanks a lot.

**Comment by yosefha-pg** [comment]
@juan-coralogix  that's awesome! Thanks :) will check it out
